/**
 * @typedef {'ai-native' | 'platform'} FeatureType
 *
 * @typedef {Object} Feature
 * @property {string} slug
 * @property {string} name
 * @property {FeatureType} type
 * @property {string|null} badge        — 'coming-soon' or null
 * @property {string} description
 * @property {string|null} screenshot   — relative public path or null
 * @property {string|null} video        — embed URL or null
 */

/** @type {Feature[]} */
export const features = [
  // ── AI-Native Features ──────────────────────────────────────────────────
  {
    slug: 'omni-channel',
    name: 'Omni Channel Communications',
    type: 'ai-native',
    badge: null,
    description:
      'Machina unifies SMS, telephony, and video into a single communication layer — with AI agents that can initiate, route, and resolve patient interactions autonomously. Every channel is logged, contextualized, and actionable without manual intervention.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'patient-profile',
    name: 'Agentic Patient Profile',
    type: 'ai-native',
    badge: null,
    description:
      'A living, AI-maintained patient record that aggregates clinical history, communication preferences, care gaps, and risk signals in real time. Agents continuously update and act on the profile — no manual data entry required.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'agentic-tasks',
    name: 'Agentic Task Completion',
    type: 'ai-native',
    badge: 'coming-soon',
    description:
      'The next evolution of the Tasks module — AI agents that don\'t just surface tasks but complete them end-to-end. From outreach to documentation to follow-up, agents close the loop without human handoff.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'agentic-queues',
    name: 'Agentic Queue Management & Task Completion',
    type: 'ai-native',
    badge: null,
    description:
      'AI agents that actively manage queue load — triaging, reassigning, and completing tasks within queues without waiting for human direction. Queue depth shrinks automatically as agents work in parallel.',
    screenshot: null,
    video: null,
  },

  // ── Platform Features ────────────────────────────────────────────────────
  {
    slug: 'workflows',
    name: 'Workflows',
    type: 'platform',
    badge: null,
    description:
      'Visual, configurable care workflows that orchestrate multi-step patient journeys across teams, channels, and time. Machina executes workflow steps autonomously, escalating to humans only when judgment is required.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'tasks',
    name: 'Tasks',
    type: 'platform',
    badge: null,
    description:
      'A structured task layer that captures every action item generated by agents, workflows, or staff — with priority scoring, assignment logic, and completion tracking built in. Nothing falls through the cracks.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'queues',
    name: 'Queues',
    type: 'platform',
    badge: null,
    description:
      'Intelligent work queues that organize patient interactions, care gaps, and staff assignments by priority, acuity, and capacity. Machina ensures the right work reaches the right person at the right time.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'workspace',
    name: 'Workspace',
    type: 'platform',
    badge: null,
    description:
      'The unified operator interface where staff, supervisors, and agents share a single working environment. Workspace surfaces the right context, tools, and actions for each role — eliminating tab-switching and context loss.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'crm',
    name: 'CRM',
    type: 'platform',
    badge: null,
    description:
      'A healthcare-native CRM that tracks every patient relationship, interaction history, and engagement signal. Machina\'s CRM is agent-aware — records update automatically as agents act, keeping data current without manual effort.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'scheduling',
    name: 'Scheduling — Maps & Appointments',
    type: 'platform',
    badge: null,
    description:
      'Intelligent scheduling that combines geographic mapping with appointment management — optimizing visit routes, reducing no-shows, and enabling agents to book, reschedule, and confirm appointments autonomously.',
    screenshot: null,
    video: null,
  },
  {
    slug: 'acd-module',
    name: 'ACD Module (Appropriate Coding)',
    type: 'platform',
    badge: null,
    description:
      'An AI-powered appropriate coding module that surfaces risk-adjusted coding opportunities in real time — ensuring accurate HCC capture, closing coding gaps, and maximizing compliant revenue without additional staff burden.',
    screenshot: null,
    video: null,
  },
];

/**
 * Returns a single feature by slug, or undefined if not found.
 * @param {string} slug
 * @returns {Feature|undefined}
 */
export function getFeatureBySlug(slug) {
  return features.find(function(f) { return f.slug === slug; });
}

/** @type {Feature[]} */
export const aiNativeFeatures = features.filter(function(f) { return f.type === 'ai-native'; });

/** @type {Feature[]} */
export const platformFeatures = features.filter(function(f) { return f.type === 'platform'; });
